export enum TittleMapEnum {
    EXPANSAO = "MAPA EXPLORATÓRIO DE VENDAS - EXPANSÃO",
    LOCALIZACAO = "MAPA EXPLORATÓRIO DE VENDAS - LOCALIZAÇÃO",
    PREVISAO = "MAPA EXPLORATÓRIO DE VENDAS - PREVISÃO",
    SISTEMATICA = "MAPA EXPLORATÓRIO DE VENDAS - SISTEMÁTICA",
}
