import { IGeoDataEntity } from "./entity/geodata.entity";

export const GeoDataStates: Array<IGeoDataEntity> = [
    { id: 12, stateCode: "ac", fileName: "geojs-12-mun.json" },
    { id: 27, stateCode: "al", fileName: "geojs-27-mun.json" },
    { id: 16, stateCode: "ap", fileName: "geojs-16-mun.json" },
    { id: 13, stateCode: "am", fileName: "geojs-13-mun.json" },
    { id: 29, stateCode: "am", fileName: "geojs-29-mun.json" },
    { id: 23, stateCode: "ce", fileName: "geojs-23-mun.json" },
    { id: 53, stateCode: "df", fileName: "geojs-53-mun.json" },
    { id: 32, stateCode: "es", fileName: "geojs-32-mun.json" },
    { id: 52, stateCode: "go", fileName: "geojs-52-mun.json" },
    { id: 21, stateCode: "ma", fileName: "geojs-21-mun.json" },
    { id: 31, stateCode: "mg", fileName: "geojs-31-mun.json" },
    { id: 51, stateCode: "mt", fileName: "geojs-51-mun.json" },
    { id: 50, stateCode: "ms", fileName: "geojs-50-mun.json" },
    { id: 15, stateCode: "pa", fileName: "geojs-15-mun.json" },
    { id: 25, stateCode: "pb", fileName: "geojs-25-mun.json" },
    { id: 26, stateCode: "pe", fileName: "geojs-26-mun.json" },
    { id: 22, stateCode: "pi", fileName: "geojs-22-mun.json" },
    { id: 41, stateCode: "pr", fileName: "geojs-41-mun.json" },
    { id: 33, stateCode: "rj", fileName: "geojs-33-mun.json" },
    { id: 24, stateCode: "rn", fileName: "geojs-24-mun.json" },
    { id: 11, stateCode: "ro", fileName: "geojs-11-mun.json" },
    { id: 14, stateCode: "rr", fileName: "geojs-14-mun.json" },
    { id: 43, stateCode: "rs", fileName: "geojs-43-mun.json" },
    { id: 42, stateCode: "sc", fileName: "geojs-42-mun.json" },
    { id: 28, stateCode: "se", fileName: "geojs-28-mun.json" },
    { id: 35, stateCode: "sp", fileName: "geojs-35-mun.json" },
    { id: 17, stateCode: "to", fileName: "geojs-17-mun.json" },
];
